name: twoMoons2016
favicon: null
layout_spectrum: 0.002629347611218691
typography_spectrum: 0.36730722058564425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6923469647299498
  lightness: 0.3285760972648859
  saturation: 0.02060308284126222
  rhythmicContrast: 0.08558738697320223
purpose: []
