name: twoMoons2016
favicon: null
layout_spectrum: 0.25145
typography_spectrum: 0.24663
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fff8'
    - '#121119'
    - '#58555e'
    - '#a7b1ca'
    - '#d0d5db'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
