name: twoMoons2016
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24663
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050412'
    - '#feffed'
    - '#54626b'
    - '#b8aa9d'
    - '#343a48'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
