name: twoMoons2016
favicon: null
layout_spectrum: 0.23962
typography_spectrum: 0.36730722058564425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020305'
    - '#2a477f'
    - '#5d81bd'
    - '#94b4e5'
    - '#daebfb'
  brandStrength: 0.6875
  lightness: 0.3285760972648859
  saturation: 0.02060308284126222
  rhythmicContrast: 0.08558738697320223
purpose: []
