name: twoMoons2016
favicon: null
layout_spectrum: 0.23962
typography_spectrum: 0.86705
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fff8'
    - '#121119'
    - '#58555e'
    - '#a7b1ca'
    - '#d0d5db'
  brandStrength: 0.125
  lightness: 0.3285760972648859
  saturation: 0.02060308284126222
  rhythmicContrast: 0.08558738697320223
purpose: []
