name: twoMoons2016
favicon: null
layout_spectrum: 0.27938
typography_spectrum: 0.24663
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afafaf'
    - '#0b0b0b'
    - '#535353'
    - '#828282'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
