name: twoMoons2016
favicon: null
layout_spectrum: 0.15455
typography_spectrum: 0.46467
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfd7d4'
    - '#bead8f'
    - '#807f7b'
    - '#514e49'
    - '#190700'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
