name: twoMoons2016
favicon: null
layout_spectrum: 0.07129
typography_spectrum: 0.24663
title: twomoons2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfd7d4'
    - '#bead8f'
    - '#807f7b'
    - '#514e49'
    - '#190700'
  brandStrength: 1
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
